version: '3.8'

services:
  api:
    build: .
    container_name: fast_api
    command: uvicorn app.main:app --host=0.0.0.0 --port=80 --reload
    volumes:
      - .:/app
    ports:
      - "8080:80"
    environment:
      - APP_NAME=FastAPI_Compose
      - DB_USERNAME=user
      - DB_PASSWORD=pwd
      - DB_NAME=fastapi
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: fast_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=fastapi

volumes:
  postgres_data: